allowBuilds:
  electron: true
  esbuild: true
minimumReleaseAgeExclude:
  - '@fallow-cli/darwin-arm64@2.99.0'
  - '@fallow-cli/darwin-x64@2.99.0'
  - '@fallow-cli/linux-arm64-gnu@2.99.0'
  - '@fallow-cli/linux-arm64-musl@2.99.0'
  - '@fallow-cli/linux-x64-gnu@2.99.0'
  - '@fallow-cli/linux-x64-musl@2.99.0'
  - '@fallow-cli/win32-arm64-msvc@2.99.0'
  - '@fallow-cli/win32-x64-msvc@2.99.0'
  - fallow@2.99.0
